name: Nuevos videos de YouTube
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflowss_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCorEC6DwpOxSTTYtpImVI_w"